### PR TITLE
Reduce flicker by rendering placeholder content during feed fetch

### PR DESCRIPTION
**Pull request by chrisrhoden**
Also changes placeholder content to be a little prettier (rounded corners)
and fixes styles a little so that the logo doesn't move to the left when the
overlay is active and the album art shrinks (this turned out to be more of a
pain than it should have been, I am happy to walk through it)

Teeing up a few other fun changes.

### CODE REVIEW

**Comment by chrisrhoden** [comment]
@cavis I'll see if I can chase that down. I'm guessing it's the CSS inliner not understanding :last-child rules properly?

**Comment by chrisrhoden** [comment]
@cavis IT IS GORGEOUS NOW

Tell me that you are not impressed with our stunning new loading state and the transition between it and fully loaded. I mean man alive this thing is a work of art

**Comment by chrisrhoden** [comment]
really like people are gonna think we're facebook or something

what is this

**Comment by cavis** [comment]
People will be all, like, totally into it and everything.

**Pull request merged**
