### PR TITLE
Various player tweaks (WIP) 

### PR DESCRIPTION
**Pull request by gcampo88**
- [X] Removes blue border from focused buttons on Chrome (addresses #73)
- [X] Removes min height & width warnings (addresses #72)
- [X] Widens preview screen of player on builder to include all optional buttons (addresses #70) 
- [X] Adds ability to include logo on player on one(+)-app-per-logo basis (addresses #29)
- [X] Enlarges scrubber bar and fixes location of line on :hover (addresses #76)

### CODE REVIEW

**Comment by kookster** [comment]
@chrisrhoden do you want to check out this approach to the logo, see how it works for RP/other orgs who might adopt? I think it aligns with our discussions.

**Comment by kookster** [comment]
@gcampo88 Looks like this is ready for review? I think maybe have @sandikbarr on this?

**Comment by gcampo88** [comment]
@kookster Sure! @sandikbarr I'll assign you for review -- let me know if you have any questions!

**Comment by sandikbarr** [comment]
Nice work!

**Pull request merged**
